### ISSUE TITLE
zstd and zstd_HC level 1 appear to be duplicate algos?

### ISSUE THREAD

**Issue by xcrh** [inikep/lzbench#13]
I gave lzbench a try on some files and eventually I noticed that if I use -eall, zstd_HC level 1 result always exactly matches zstd on everything I've tested. Both speeds and compressed size are identical. At the end of day it looks pretty much like identical algo tested twice.

It typically looks like this:
```
zstd_HC v0.3.6 level 1          53 MB/s    165 MB/s      3551054  28.89
zstd v0.3.6                     52 MB/s    165 MB/s      3551054  28.89
```
...so my guess would be zstd HC level 1 isn't really necessary in -eall?

**Comment by tobijdc** [comment]
This is correct zstd HC level 1 redirects to zstd (see zstd source code)

**Comment by inikep** [comment]
I changed to "zstd/zstd_HC,2,5,9,13,17,20"
