### ISSUE TITLE
Highest levels are missing for LZ4/LZ5 in -eall?

### ISSUE THREAD

**Issue by xcrh** [inikep/lzbench#15]
After some grinding through compression algos code I've stumbled on the fact LZ4/5 seems to have level 16 as maximum in their HC versions. Requesting lvl 16 manually leads to somewhat smaller data in some cases.  

Same was true about crush, which had level 2, previously not included anywhere. Yet giving better compression vs lvl 0/1 and in fact being competitive against best/slowest LZs not using entropy coding in terms of ratio, if I've got it right. Though now it fixed and crush lvl 2 included to "all".

In some use cases one may want to get absolutely most from pre-existing compressoin engine, taking little care of compression speed. For the very same reason it can be interesting idea to add zophli or something like this to benchmark. This is something like zlib_HC, for cases where we care to get absolutely best from some pre-existing algo :)

**Comment by inikep** [comment]
Thanks for info. Highest levels for LZ4/LZ5 are now included in -eall (dev branch).
