### ISSUE TITLE
Consider disabling pithy

### ISSUE THREAD

**Issue by nemequ** [inikep/lzbench#16]
As part of my efforts [to fuzz compression libraries](https://github.com/nemequ/compfuzz/), I recently tested pithy and found some vulnerabilities.  The author has not responded to email about the issue for over a month, nor the pull request filed against the project, so AFAICT it's abandoned.

I'm not sure whether or not it is appropriate for this project to keep supporting pithy or not.  It obviously shouldn't be used in production code, but lzbench isn't really intended for production code…  I guess the distinction should be whether lzbench is intended to help people choose a compression library for their code (in which case it would be better not to include pithy), or as a tool for people writing compression libraries (in which case it would be better to include it).

**Comment by inikep** [comment]
Actually I see lzbench as a program to find bugs in compressors. I even report decompression errors in my results that everyone can see. So far I've seen the following errors (described in lzbench.h and README.md):
"shrinker/wflz/lzmat" // these can SEGFAULT with gcc -O3
"pithy/lzmat" // decompression error (returns 0)
"density" // decompression error (shortened output)
Only gipfeli was fixed.

**Comment by nemequ** [comment]
Sorry, should have responded to this sooner.  I also filed [a similar issue against TurboBench](https://github.com/powturbo/TurboBench/issues/3), you might want to take a look.  I think the "solution" there (a disclaimer that some codecs aren't secure, and a link the the [CompFuzz Results](https://github.com/nemequ/compfuzz/wiki/Results) page) should work here, too.

FWIW, when you do encounter issues please let me know somehow.  Editing the yourself (the Results page is a wiki) would be great, but you can also file an issue, e-mail me, poke me on IRC (I lurk in #squash on FreeNode), etc.  I'd like to keep that list as comprehensive and up-to-date as I can.

**Comment by xcrh** [comment]
From practical standpoint, I do not think someone can reasonalby attack lzbench itself in anyhow sensible/unexpected/troublesome ways. So disabling algo here makes a little sense. But I guess troublesome things should be mentioned. 

And to be fair:
1) LZ4 historically had one securty problem in handling its own bitstream. It encodes numbers by adding next byte of stream and can repeat it. It raises interesting question: what if you feed it with fairly large malicious stream, increasing number so much it overflows? Someone eventually found answer: it going to be VULN. It takes unusually large chunk of data, it must be above 16 megabytes to overflow counter this way, it takes a lot of additions. Parser was not prepared to such abuse. Now it has been fixed.

2) Fairly similar problem has also been spotted in LZO as well. And fixed around the very same time frame, because these 2 vulns were quite similar in their idea and so they've got caught both at once.

..so from purely historic perspective, LZ4 and LZO had vuln in handling their bitstreams. Both fixed to the date.

**Comment by nemequ** [comment]
> From practical standpoint, I do not think someone can reasonalby attack lzbench itself in anyhow sensible/unexpected/troublesome ways. So disabling algo here makes a little sense.

I agree that it doesn't really matter for lzbench.  My concern is people using lzbench as a benchmark to help choose an algorithm to use in their software; lzbench is effectively presenting pithy as a valid choice, but there isn't really a way to tell that pithy is vulnerable.

> ..so from purely historic perspective, LZ4 and LZO had vuln in handling their bitstreams. Both fixed to the date.

Yes, and we're currently finding vulnerabilities in lots of compression software.  Going through the list, I have found issues myself in blosc, density, gipfeli, csc, libzling, lzmat, pithy, wflz, and zstd (most of them have been fixed).

The problem isn't that there is (or was) a security vulnerability.  The problem is that there is a vulnerability in pithy *and no indication it will be fixed*.  I have reported the issue via e-mail, no response.  I would file a bug report but the issue tracker is disabled.  There has been no response to the PR for Windows support (not a vulnerability, but indicative of the project's level of activity).  AFAICT the author has not been active on github for several years, and the project is inactive.

I don't actually mind the project being inactive, but inactive with a security vulnerability is extremely problematic.

**Comment by nemequ** [comment]
FWIW, I think something like this would be appropriate:

```diff
diff --git a/README.md b/README.md
index 2ff776c..e6fe740 100644
--- a/README.md
+++ b/README.md
@@ -55,6 +55,11 @@ To remove one of compressors you can add -DBENCH_REMOVE_XXX to $DEFINES in Makef
 
 Supported compressors
 -------------------------
+**Warning**: some of the compressors listed here have security issues
+and/or are no longer maintained.  For information about the security
+of the various compressors, see the
+[CompFuzz Results](https://github.com/nemequ/compfuzz/wiki/Results)
+page.
 ```
 blosclz 2015-11-10
 brieflz 1.1.0
```

**Comment by inikep** [comment]
A good idea. Added in https://github.com/inikep/lzbench/tree/dev

**Comment by xcrh** [comment]
I guess it is "valid choice" in terms of evaluating algo performance & most obvious problems on realistic data, which seems to be goal of lzbench. Furthermore, in some use cases one decompresses only "trusted" data and does not deals with arbitrary external input, so it may or may not be problem.

Also, lzbench manages to make a call into plenty of algos which were not even really meant to be used as library or algos embedded into program at all and vary wildly, from something close to prototypes to established libs. So I would consider it as a tool, useful for experiments and prototypes as well. So I'm not sure it should be THAT harsh on algos. However, it seems to be perfectly fair to warn others about discovered properties of various algos, etc. So either autor or somene else have chances to fix it. Actually, if authors do not fix it for a while, lzbench can provide alternate, fixed version (if it exist) and clearly mark one as such. It aready been a case for gipfeli, if I remember it properly. And as you can see I'm aware it wasn't "vanilla" lib version for some time.

> Yes, and we're currently finding vulnerabilities in lots of compression software. 
It is somewhat fundamental problem: writing software in secure ways requires changing thinking to "security minded" one. I.e. normally programmer would just try to reach goal. But this way of thinking may or may not include weird/boundary conditions. Like "what if attacker would feed us with 16M stream, trying to exceed 32-bit sum?".

> The problem is that there is a vulnerability in pithy and no indication it will be fixed.
I'm agree its bad. But completely disabling algo in lzbench sounds like overkill. Yet, I think making the fact some libs have major issues more visible is a good idea. Actually, some libs can expose other fancy bugs, while not being a vulns, they can turn out to be a very unpleasant surprises. Maybe lzbench can display another column with e.g. like this:

[code]
          ...usual columns...  Notes
somelib:     ...               1, 2
somelib2:    ...               2, 3

1: fails decompression on ARM
2: contains vulnerability, see readme!
3: could crash if built with gcc 4.9+ -O3
[/code]

**Comment by nemequ** [comment]
> Furthermore, in some use cases one decompresses only "trusted" data and does not deals with arbitrary external input, so it may or may not be problem.

That's a good point, but even in such a situation I think people should feel pretty uncomfortable about using insecure software.  For one thing, projects tend to sprawl; just because something will only be used with trusted input today doesn't mean the same will be true tomorrow, and most people aren't very good with thinking about how security requirements can subtly shift during such changes.  

Another (perhaps more troubling) issue is that people also aren't very good with thinking about security during development; I've seen lots of people think "trusted" meant that data comes from a logged in user that's not trying to be malicious, without thinking about what happens if that user's account is compromised.

Sure, some people are capable of making good security decisions.  Many (in my experience most) don't.  Whenever possible, security needs to be hard to get wrong, not easy.  If these codecs were outperforming their competition by a wide margin it might be worth the time and effort to educate people on when they can be used securely (not to mention the risk of it not getting through), but they're not.

> Actually, if authors do not fix it for a while, lzbench can provide alternate, fixed version (if it exist) and clearly mark one as such.

I'd love to see someone fork the repo and provide a fixed version.  As long as the documentation (i.e., the README) gave proper credit and a clear rationale for the fork I would just start treating that as the canonical source, point to it in documentation, etc.  There are already a couple abandoned projects listed on the CompFuzz Results page which could benefit from a new home.

> It aready been a case for gipfeli, if I remember it properly. And as you can see I'm aware it wasn't "vanilla" lib version for some time.

Maybe you're thinking of a different codec.  We have fixed a couple of bugs to get it working in Squash (especially on Windows, for which there is still one last PR waiting to be merged), but the API hasn't changed.  IIRC lzbench is (recently) forked from m^2's work, so http://encode.ru/threads/2160-Squash-and-the-Squash-Benchmark?p=43136&viewfull=1#post43136 should be relevant.

> Maybe lzbench can display another column with e.g. like this:

That would be really nice, but I think it would be a pain to keep it up to date.  I'd really like to see a central location for this information, which I'm trying to make the CompFuzz Results suitable for.  That allows other projects, such as Squash and TurboBench, to benefit from the list as well, and it's a single location to (try to) keep up to date.

**Comment by xcrh** [comment]
> people should feel pretty uncomfortable about using insecure software.

If I would e.g. decompress kernel, I take care to put valid data. Should attacker be able to put bad data... it is far more logical just to put malicious kernel, not to try to hack compressor instead. Of course there're plenty of other cases, this one to illustrate how it could look like where it not a big deal. Though I think it is good idea to think twice anyway. It can get tempting to reuse code :)

>  people also aren't very good with thinking about security during development

That's a valid point, but I suspect such people do not use lzbench either. People like this would also usually select either from couple of most popular algos or maybe trust loudest marketing around and I'm not sure how many people like this would use lzbench at all.

> Maybe you're thinking of a different codec. 

lzbench used gipfeli with some fixes from Joerg Ibsen for some time. Now it uses standard version IIRC.

And whatever, but I like your efforts to keep things secured, thanks for it. So tracking it in some up to date manner looks like good idea.

**Comment by nemequ** [comment]
> That's a valid point, but I suspect such people do not use lzbench either. People like this would also usually select either from couple of most popular algos or maybe trust loudest marketing around and I'm not sure how many people like this would use lzbench at all.

Depressingly true :(

> lzbench used gipfeli with some fixes from Joerg Ibsen for some time. Now it uses standard version IIRC.

Oh.  IIRC those were merged into gipfeli pretty quickly, so I didn't even think about them.  They weren't API related, though; mostly just fixing Windows issues, plus a bug that didn't manifest on linux or os x.

I'm satisfied with the change to the README; anyone object to closing the issue?
