### ISSUE TITLE
possible to add non lz compressors

### ISSUE THREAD

**Issue by rdp** [inikep/lzbench#21]
Since there's no google group sounding it out here.
Might be nice to add a few more compressors (that aren't lz) just in the theory that "more data is good!" or what not.  Though I know it goes against the name and scope of the project :)

(ex: zpaq, bsc, whatever else squash has that lzbench doesn't)

Thanks for the benchmarks! :)

**Comment by inikep** [comment]
Sure it can be done but it requires a support from open-source community.

**Comment by shrx** [comment]
+1 for zpaq

**Comment by travisdowns** [comment]
Out of curiosity, there is no actual technical limitations to adding non-LZ compressors, right? The project description somehow lists the types of compressors included, but I assume that's just kind of a loose filter with the idea of including the "faster" end of the compressing spectrum. If you had a compressor that wasn't LZ but performed well (especially if better than some existing included ones), would @inikep allow it it be included?

**Comment by inikep** [comment]
Sure, I will allow commits with non-LZ compressors. But I may leave them disabled by default if there will be some compilation issues. For example, I had some problems with auto-disabling glza (requires gcc 4.9+) and LZSSE (requires SSE).

**Comment by tansy** [comment]
I happened to add bzip2 codec to bench. It is pretty standard compressor so I thought it deserves attention.
I didn't do a commit - git is a bit magical to me but I made a patch to newest version if anyone is interested.

**Comment by tansy** [comment]
I happened to add bzip2 codec to the bench. It is pretty standard compressor so I thought it deserves attention.
I didn't do a commit - git is a bit magical to me but I made a patch to the newest version if anyone is interested.

**Comment by tansy** [comment]
I happened to add bzip2 codec to the bench. It is pretty standard compressor so I thought it deserves attention.
I didn't do a commit - git is a bit magical to me but I made a patch to the newest version if anyone is interested.

[lzbench-1.7.3-2019.04.30+bzip2-master.diff.gz](https://github.com/inikep/lzbench/files/3143936/lzbench-1.7.3-2019.04.30%2Bbzip2-master.diff.gz)

**Comment by tansy** [comment]
I happened to add bzip2 codec to the lzbench. It is pretty standard compressor so I thought it deserves attention.
I didn't do a commit - git is a bit magical to me but I made a patch to the newest version if anyone is interested. Maybe it fill find a place in the bench.

[lzbench-1.7.3-2019.03.08+bzip2-master.diff.gz](https://github.com/inikep/lzbench/files/3143959/lzbench-1.7.3-2019.03.08%2Bbzip2-master.diff.gz)

**Comment by inikep** [comment]
bzip2 was added at https://github.com/inikep/lzbench/commit/278cd4981f3622c4d765c7527ceb9c272325a788
Thanks for the patch

**Comment by tansy** [comment]
You're welcome. Hope it was good quality.

**Comment by inikep** [comment]
I wound not merge it otherwise. Thanks again.
