### ISSUE TITLE
Problems with statistics.

### ISSUE THREAD

**Issue by reedacartwright** [inikep/lzbench#24]
In `lzbench_test`, the compression and decompression steps are run 1 or more times until the total time is above a threshold. If the time an iteration takes is above 10000 nanoseconds, then that time is pushed onto a vector.
 - https://github.com/inikep/lzbench/blob/master/_lzbench/lzbench.cpp#L315
 - https://github.com/inikep/lzbench/blob/master/_lzbench/lzbench.cpp#L348

After that time is done, the average time is also placed onto the vector.
 - https://github.com/inikep/lzbench/blob/master/_lzbench/lzbench.cpp#L354
 - https://github.com/inikep/lzbench/blob/master/_lzbench/lzbench.cpp#L321

Because there are two different types of values on the vector, then the statistics (fastest, average, median) collected on the algorithms are not as accurate as they could be.

**Comment by inikep** [comment]
There is an issue with benchmarking files smaller than 100 KB and with decompressors with speed of 3 GB/s or faster: subsequent measurements may vary considerably. To solve this problem I decided that it is better to have only average value and `if (nanosec >= 10000)` detect this case. For bigger files or slower compressors/decompressors the condition `if (nanosec >= 10000)` is always fulfilled therefore statistics should be as accurate as possible.

**Comment by reedacartwright** [comment]
`if (nanosec >= 10000)` you push raw times onto the `ctime` vector: `ctime.push_back(nanosec);`  But you also push average time on the vector as well.   `ctime.push_back(nanosec/i);`

Therefore, at the end of the run `ctime` can contain both individual cycle times and average times.

**Comment by inikep** [comment]
Yes, a vector should contain hundreds/thousands of individual times and the additional average time. When you look at the vector after sorting:
a) fastest - the additional average time for sure doesn't change anything
b) average - addition of average time shouldn't change results
c) median - this can be slightly different but only -1 or +1 place
