### ISSUE TITLE
update lz4 to 1.7.5

### ISSUE THREAD

**Issue by svpv** [inikep/lzbench#32]
Could you please update lz4 to the latest version? I have an important change in github.com/svpv/lzbench which I believe speeds up 'lz4hc -1' by 10-20%. But it needs more profiling, specifically with the recent version of lz4.

**Comment by inikep** [comment]
Updated with https://github.com/inikep/lzbench/commit/db1d5410950c5a495f26dc5e9a3e7fd015b8705c
