### ISSUE TITLE
xpack compiling error

### ISSUE THREAD

**Issue by darouwan** [inikep/lzbench#36]
xpack/lib/xpack_compress.c:120: warning: declaration does not declare anything
xpack/lib/xpack_compress.c:121: warning: declaration does not declare anything
xpack/lib/xpack_compress.c: In function ‘write_block’:
xpack/lib/xpack_compress.c:1185: error: ‘struct codes’ has no member named ‘literal_state_counts’
xpack/lib/xpack_compress.c:1191: error: ‘struct codes’ has no member named ‘litrunlen_state_counts’
xpack/lib/xpack_compress.c:1197: error: ‘struct codes’ has no member named ‘length_state_counts’
xpack/lib/xpack_compress.c:1203: error: ‘struct codes’ has no member named ‘offset_state_counts’
xpack/lib/xpack_compress.c:1210: error: ‘struct codes’ has no member named ‘aligned_state_counts’
xpack/lib/xpack_compress.c:1222: error: ‘struct codes’ has no member named ‘aligned_state_counts’
xpack/lib/xpack_compress.c:1222: error: ‘struct codes’ has no member named ‘state_counts’
xpack/lib/xpack_compress.c:1222: error: ‘struct codes’ has no member named ‘state_counts’
xpack/lib/xpack_compress.c:1226: error: ‘struct codes’ has no member named ‘state_counts’
xpack/lib/xpack_compress.c:1226: error: ‘struct codes’ has no member named ‘state_counts’
xpack/lib/xpack_compress.c:1230: error: ‘struct codes’ has no member named ‘state_counts’
xpack/lib/xpack_compress.c:1254: error: ‘struct codes’ has no member named ‘literal_state_counts’
xpack/lib/xpack_compress.c:1260: error: ‘struct codes’ has no member named ‘litrunlen_state_counts’
xpack/lib/xpack_compress.c:1266: error: ‘struct codes’ has no member named ‘length_state_counts’
xpack/lib/xpack_compress.c:1272: error: ‘struct codes’ has no member named ‘offset_state_counts’
xpack/lib/xpack_compress.c:1279: error: ‘struct codes’ has no member named ‘aligned_state_counts’
make: *** [xpack/lib/xpack_compress.o] Error 1

**Comment by darouwan** [comment]
and another error:
In file included from density/block_decode.h:40,
                 from density/block_decode.c:35:
density/main_header.h:55: warning: declaration does not declare anything
density/block_decode.c: In function ‘density_block_decode_init’:
density/block_decode.c:123: error: ‘density_main_header_parameters’ has no member named ‘as_bytes’
make: *** [density/block_decode.o] Error 1

**Comment by darouwan** [comment]
One more error:

_lzbench/compressors.cpp:1436: error: expected unqualified-id before ‘__null’
_lzbench/compressors.cpp:1436: error: expected initializer before ‘__null’
_lzbench/compressors.cpp:1446: error: expected unqualified-id before ‘__null’
_lzbench/compressors.cpp:1455: error: expected unqualified-id before ‘__null’
_lzbench/compressors.cpp:1463: error: expected unqualified-id before ‘__null’

...os is cent os 6.3

**Comment by inikep** [comment]
What kind of compiler do you have? Can you give me results of `cc -v` and `gcc -v`.

**Comment by cailongjian** [comment]
the same problem,my gcc -v res is
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --enable-threads=posix --prefix=/usr --with-local-prefix=/usr/local --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.1.2 --enable-ssp --disable-libssp --disable-libgcj --with-slibdir=/lib64 --with-system-zlib --enable-shared --enable-__cxa_atexit --enable-libstdcxx-allocator=new --program-suffix= --enable-version-specific-runtime-libs --without-system-libunwind --with-cpu=generic --host=x86_64-suse-linux
Thread model: posix
gcc version 4.1.2 20070115 (prerelease) (SUSE Linux)

and cc -v res is 
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --enable-threads=posix --prefix=/usr --with-local-prefix=/usr/local --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.1.2 --enable-ssp --disable-libssp --disable-libgcj --with-slibdir=/lib64 --with-system-zlib --enable-shared --enable-__cxa_atexit --enable-libstdcxx-allocator=new --program-suffix= --enable-version-specific-runtime-libs --without-system-libunwind --with-cpu=generic --host=x86_64-suse-linux
Thread model: posix
gcc version 4.1.2 20070115 (prerelease) (SUSE Linux)
