### ISSUE TITLE
UCL algos selection is confusing.

### ISSUE THREAD

**Issue by xcrh** [inikep/lzbench#4]
I haven't understood how to select UCL algos via -e, and if I just ask for ucl, results are confusing as well.

If I would just ask for UCL, I do get strange results:
- Algos from 11 to 39 would be tested.
- Algos 20 and 30 appear to be just the very same as memcpy. Are there any reasons to test them?
- I know UCL haves 3 algos in its core: nrv2b, nrv2d and nrv2e, this has been shown in your results published on encode.ru or somewhere like this,  but I'm not really sure how these maps to numbers, and if they do at all. This is just plain confusing.

**Comment by xcrh** [comment]
Btw, qute same idea applies to LZO. I fail to understand which exact LZO algos it uses. Say what is level 5999? And what is 1999? Sure, LZO haves plenty of algos and it can be confusing itself. And naming them by levels seems to make it even harder to get idea what algos are actually used without thorough grinding through source code (which seems to be the only way to understand it properly).

**Comment by inikep** [comment]
thanks, fixed in "dev"
