### ISSUE TITLE
build error on Suse 12.2

### ISSUE THREAD

**Issue by yexushiran** [inikep/lzbench#42]
Hi, 
I have built lzbench 1.7.2 on SUSE Linux Enterprise Server 12 (x86_64). Unfortunately it fails due to a lib link error:
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lrt
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lpthread
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lm
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lc

I have changed the Makefile, removed "LDFLAGS += -lrt -static" line 54 and "LDFLAGS += -lpthread" line 56 since the logic says if the system is not Darwin. It is a static lib link problem. This might be an issue.

BR,
Xiao

**Comment by inikep** [comment]
Hi, did your fixes solved the issue?

**Comment by yexushiran** [comment]
Yes, it works.
