### ISSUE TITLE
LZSSE requirement check is incomplete

### ISSUE THREAD

**Issue by danfe** [inikep/lzbench#46]
Currently, LZSSE code is built if CPU supports SSE4.1 intrinsics, which is not enough if CPU is running in 32-bit mode (e.g., `_mm_cvtsi64_si128` is 64-bit only).  Consider the patch below which enforces the check:
```diff
-# LZSSE requires gcc with support of __SSE4_1__
-ifeq ($(shell echo|$(CC) -dM -E - -march=native|grep -c SSE4_1), 0)
+# LZSSE requires compiler with __SSE4_1__ support and 64-bit CPU
+ifneq ($(shell echo|$(CC) -dM -E - -march=native|egrep -c '__(SSE4_1|x86_64)__'), 2)
        DONT_BUILD_LZSSE ?= 1
 endif
```

**Comment by inikep** [comment]
Thanks. Looks good, can you make pull request with this change? It will run all Travis tests automatically.

**Comment by danfe** [comment]
Sorry, but I suck at git and pull requests, I can only deal with patches.  Let's hope someone else would see this issue and do what you ask if they find it useful.

**Comment by inikep** [comment]
I will do it when I will find some time, thanks

**Comment by inikep** [comment]
Changes were merged, thanks
