### ISSUE TITLE
Lzbench build issues

### ISSUE THREAD

**Issue by jbirajda** [inikep/lzbench#48]
Hi ,
  I'm trying to build  lzbench using gcc 6.1.0 and seeing below elab errors:
xpack/lib/xpack_compress.c:1185: error: 'struct codes' has no member named 'literal_state_counts'
xpack/lib/xpack_compress.c:1191: error: 'struct codes' has no member named 'litrunlen_state_counts'
xpack/lib/xpack_compress.c:1197: error: 'struct codes' has no member named 'length_state_counts'
xpack/lib/xpack_compress.c:1203: error: 'struct codes' has no member named 'offset_state_counts'
xpack/lib/xpack_compress.c:1210: error: 'struct codes' has no member named 'aligned_state_counts'
xpack/lib/xpack_compress.c:1222: error: 'struct codes' has no member named 'aligned_state_counts'
xpack/lib/xpack_compress.c:1222: error: 'struct codes' has no member named 'state_counts'
xpack/lib/xpack_compress.c:1222: error: 'struct codes' has no member named 'state_counts'
xpack/lib/xpack_compress.c:1226: error: 'struct codes' has no member named 'state_counts'
xpack/lib/xpack_compress.c:1226: error: 'struct codes' has no member named 'state_counts'
xpack/lib/xpack_compress.c:1230: error: 'struct codes' has no member named 'state_counts'
xpack/lib/xpack_compress.c:1254: error: 'struct codes' has no member named 'literal_state_counts'
xpack/lib/xpack_compress.c:1260: error: 'struct codes' has no member named 'litrunlen_state_counts'
xpack/lib/xpack_compress.c:1266: error: 'struct codes' has no member named 'length_state_counts'
xpack/lib/xpack_compress.c:1272: error: 'struct codes' has no member named 'offset_state_counts'
xpack/lib/xpack_compress.c:1279: error: 'struct codes' has no member named 'aligned_state_counts'
make: *** [xpack/lib/xpack_compress.o] Error 1
how can I resolve them?

**Comment by tansy** [comment]
I know it's late response and error is kind of confusing but have tried to compile xpack on its own (`cd xpack && make`)? I just checked xpack and it compiles without any issue.

**Comment by tansy** [comment]
As there is a thread about building issues I wanted to attach.
I was trying new version (2019/03/08) and noticed that after build lzham codecs disappeared from executable. I didn't turn them off (DONT_BUILD_LZHAM) and lzham codec was compiled. All objects (lzham/*.o) were created and linked into executable. I also checked their presence in executable. Still the lzham codecs disappeared from list (`lzbench -l`).
I also tested older version (2018/01/05) and it is not happening.
It happens in tdm-gcc-5.1.0-mingw32 and gcc-7.3.0-mingw32. Also checked gcc-7.3.0-mingw64 and it is pretty fine*.
I also tested it under linux and it's ok there.

What can I do track down the issue?

* lzham fails with `Compression test failed with status 6!`; I'll investigate it but it doesn't seem to have anything to do with lzbench as other codecs do just fine.

**Comment by tansy** [comment]
As there is a thread about building issues I wanted to attach.
I was trying new version (2019/03/08) and noticed that after build lzham codecs disappeared from executable. I didn't turn them off (DONT_BUILD_LZHAM) and lzham codec was compiled. All objects (`lzham/*.o`) were created and linked into executable. I also checked their presence in executable. Still the lzham codecs disappeared from list (`lzbench -l`).
I also tested older version (2018/01/05) and it is not happening.
It happens in tdm-gcc-5.1.0-mingw32 and gcc-7.3.0-mingw32. Also checked gcc-7.3.0-mingw64 and it is pretty fine&#185;.
I also tested it under linux and it's ok there.

What can I do track down the issue?

&#185; lzham fails with Compression test failed with status 6!; I'll investigate it but it doesn't seem to have anything to do with lzbench as other codecs do just fine.

**Comment by tansy** [comment]
As there is a thread about building issues I wanted to attach.
I was trying new version (2019/03/08) and noticed that after build lzham codecs disappeared from executable. I didn't turn them off (`DONT_BUILD_LZHA`) and lzham codec was compiled. All objects (`lzham/*.o`) were created and linked into executable. I also checked their presence in executable. Still the lzham codecs disappeared from list (`lzbench -l`).
I also tested older version (2018/01/05) and it is not happening.
It happens in tdm-gcc-5.1.0-mingw32 and gcc-7.3.0-mingw32. Also checked gcc-7.3.0-mingw64 and it is pretty fine&#185;.
I also tested it under linux and it's ok there.

What can I do track down the issue?

&#185; lzham fails with `Compression test failed with status 6!`; I'll investigate it but it doesn't seem to have anything to do with lzbench as other codecs do just fine.

**Comment by inikep** [comment]
Please try the newest release. I fixed all issues with clang up to clang-9 and gcc up to gcc-9.

**Comment by tansy** [comment]
I didn't have time to test new release but I found typo, as I guess, in *_lzbench/lzbench.cpp* in my "archive" I didn't report yet. In line 721:

`fprintf(stderr, " -e#   #=compressors separated by '/' with parameters specified after ',' (deflt=fast)\n");`

should be `(default=fast)`. It has no effect on actual program's work as it's only help displayed but typo nevertheless.
