### ISSUE TITLE
Compression/Decompression rates

### ISSUE THREAD

**Issue by waitaria** [inikep/lzbench#53]
Hello, I had a question regarding the reporting of the rates for the compression and decompression algorithms. Are the rates (given in MB/s) reported for the output or input of the compression? How about the decompression? IE does a decompression speed of 500 MB/s mean that the decompression algorithm outputs 500MB of uncompressed data each second, or does it decompress 500MB of compressed data into, say, 1000MB of raw data each second?

**Comment by inikep** [comment]
Hi, compression and decompression speed is measured regarding to the size of original/uncompressed data. This sentence is true: decompression speed of 500 MB/s mean that the decompression algorithm outputs 500MB of uncompressed data each second.

**Comment by waitaria** [comment]
Thanks a lot for your help.
