### ISSUE TITLE
"./lzbench -elzlib,0 -j -r -s1000 /dir" freezes on this input

### ISSUE THREAD

**Issue by safinaskar** [inikep/lzbench#61]
Steps to reproduce:
* Create a directory, say, `/tmp/a` (you should have enough free space on that partition)
* Unzip this file to that directory: [00000601.ppm.gz](https://github.com/inikep/lzbench/files/3951661/00000601.ppm.gz) under name `1.ppm` (this is normal ppm image)
* Create 299 more copies of this file (so total number is 300), for example (in bash): `cd /tmp/a; for I in {2..300}; do cp 1.ppm $I.ppm; done`
* Run this: `time -p ./lzbench -elzlib,0 -j -r -x /tmp/a`
* The command will finish in some reasonable time, for my computer this is 47.20 seconds
* Now run this: `time -p ./lzbench -elzlib,0 -j -r -x -s1000 /tmp/a`
* The command will not finish in 4 minutes and it seems it will run forever. This is very strange, because, as well as I understand, adding `-s1000` should not slow down computation, so, this computation should take no more time than computation without `-s1000`, i. e. 47.20 seconds

My system is Debian stretch amd64 (with some packages from Debian buster). Linux 4.19.0. GCC 6.3.0. Tests performed on real hardware

**Comment by inikep** [comment]
Thanks for a bug report. I fixed the issue at https://github.com/inikep/lzbench/commit/3ecc9bfe5b980048c6e363fb2747ddf606422006

**Comment by safinaskar** [comment]
Thanks. I tested. It works
