### ISSUE TITLE
LZMAT library could crash on compressing large files.

### ISSUE THREAD

**Issue by xcrh** [inikep/lzbench#7]
Configuration: 
lzbench: commit 5937923
OS: Xubuntu 64-bit, 15.10.
Compler: gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)
Flags: defauts from makefile, only BUILD_SYSTEM=linux uncommented.

Description:
Another day, another crash... to reproduce: 
1) Build lzbench with default compile flags on similar configuration. 
2) Try to compress some reasonably large file.
3) Take a look what happens, preferrably under debugger.

Result: 
 Crash could occur in lzmat compressor if file is large enough.
 Files smaller than few hundreds kb or so do not cause crash, but attempt to compress file larger than megabyte causes crash in lzmat_encode. 
 For example, attempt to compress lzmabench itself :) would fail.

Note: 
1) This algo presents in -eall, so for almost all reasonably large files lzbench just dies in the middle. Which is kinda unfortunate.
2) It seems author's page is down and I failed to find reasonable way to file a bug.

 ```
Program received signal SIGSEGV, Segmentation fault.
0x000000000056e6da in lzmat_encode ()
(gdb) bt full
#0  0x000000000056e6da in lzmat_encode ()
No symbol table info available.
#1  0x00000000005ce28d in lzbench_lzmat_compress(char*, unsigned long, char*, unsigned long, unsigned long, unsigned long, unsigned long)
    ()
No symbol table info available.
#2  0x00000000005bfdff in lzbench_compress(long (*)(char*, unsigned long, char*, unsigned long, unsigned long, unsigned long, unsigned long), unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >&, unsigned char*, unsigned long, unsigned char*, unsigned long, unsigned long, unsigned long, unsigned long) ()
No symbol table info available.
#3  0x00000000005c1661 in lzbench_test(compressor_desc_t const*, int, int, unsigned long, int, unsigned char*, unsigned long, unsigned char*, unsigned long, unsigned char*, timespec, unsigned long, unsigned long, unsigned long) [clone .constprop.142] ()
No symbol table info available.
#4  0x00000000005c203d in lzbench_test_with_params(char*, int, unsigned long, int, unsigned char*, unsigned long, unsigned char*, unsigned long, unsigned char*, timespec) ()
No symbol table info available.
#5  0x00000000005c1e0f in lzbench_test_with_params(char*, int, unsigned long, int, unsigned char*, unsigned long, unsigned char*, unsigned long, unsigned char*, timespec) ()
No symbol table info available.
#6  0x00000000005c2422 in lzbenchmark(_IO_FILE*, char*, int, unsigned int, int) ()
No symbol table info available.
#7  0x0000000000401267 in main ()
No symbol table info available.
```

**Comment by inikep** [comment]
If you are using debugger you can compile lzbench with "BUILD_TYPE=debug" (sometimes errors disappear after this).
I couldn't reproduce your SEGFAULT. In my experiments I only found decompression error of lzmat.
So far I moved "lzmat" to the end of a compressors list and now it will be compiled with -O2 option.
I commited all changes to github so you can try if it helps:
https://github.com/inikep/lzbench/tree/dev

**Comment by inikep** [comment]
Thanks for testing. I will leave -O2 for lzmat and wflz. They will be also in the end of a compressor list just in case.
