### ISSUE TITLE
Linking errors when built with -fno-common (Clang 11, GCC 10)

### ISSUE THREAD

**Issue by danfe** [inikep/lzbench#76]
Recent versions of compilers no longer allow duplicated symbols in the object files when linking final executable, and lzbench suffers from this.  Particularly, there are lots of duplicates in the `glza/GLZA{de,en}code.c` files.  I'll waive the actual patch as it's rather mechanical and the problem is easily reproducible locally.  To force the new behavior with older compilers, just build lzbench with `MOREFLAGS=-fno-common`.

**Comment by inikep** [comment]
The issue should be fixed with https://github.com/inikep/lzbench/releases/tag/v1.8.1

**Comment by danfe** [comment]
It does indeed seems fixed now, thank you.
