### ISSUE TITLE
Ask about zstd-1.4.5 support in lzbench

### ISSUE THREAD

**Issue by liusheng** [inikep/lzbench#78]
Hi,
According to the Zstd latest version `1.4.5` release page, the Benchmark results shows zstd-1.4.5 has been run with lzbench, but I cannot the support of zstd-1.4.5 in lzbench repo. Is there something missing ?
Thanks.

**Comment by jinfeihan57** [comment]
The latest zstd update in lzbench is 1.4.4. zstd 1.4.5 has not been updated to lzbench.
It's a good point and I'll update it.  recently.

**Comment by liusheng** [comment]
@jinfeihan57 thanks for your clarification, it's greate to support zstd-1.4.5 in lzbench.

**Comment by inikep** [comment]
zstd-1.4.5 was merged to lzbench
