### ISSUE TITLE
"make clean" does not removes lzbench executable out of the way.

### ISSUE THREAD

**Issue by xcrh** [inikep/lzbench#8]
Configuration:
lzbench: commit 5937923
OS: Xubuntu 64-bit, 15.10.
Compler: gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)
Flags: defauts from makefile, only BUILD_SYSTEM=linux uncommented.

To reproduce:
 1) Build lzbench.
 2) run make clean.

Result:
 Lzbench executable stays in build tree. Everything else is fine.

Expected
 Lzbench executable also removed. There is little point to trash all object files but leave main executable if I want clean build.

**Comment by inikep** [comment]
fixed in "dev"
