### ISSUE TITLE
Makefile doesn't work on Windows10

### ISSUE THREAD

**Issue by zhangyaya** [inikep/lzbench#92]
Log as below: 
'cc' is not recognized as an internal or external command,
operable program or batch file.
'[' is not recognized as an internal or external command,
operable program or batch file.
'[' is not recognized as an internal or external command,
operable program or batch file.
'cc' is not recognized as an internal or external command,
operable program or batch file.
'cc' is not recognized as an internal or external command,
operable program or batch file.
'[' is not recognized as an internal or external command,
operable program or batch file.
'[' is not recognized as an internal or external command,
operable program or batch file.
process_begin: CreateProcess(NULL, uname, ...) failed.
The syntax of the command is incorrect.
Makefile:321: recipe for target 'bzip2/blocksort.o' failed
make: *** [bzip2/blocksort.o] Error 1
System environment:
Windows 10 1909
GCC: (MinGW.org GCC Build-2) 9.2.0

**Comment by jinfeihan57** [comment]
This Makefile is working on linux & mac.
If you using windows ,please try [cygwin](https://www.cygwin.com/).

**Comment by inikep** [comment]
Lzbench works fine with MinGW: https://ci.appveyor.com/project/inikep/lzbench
You have to use `sh` or `bash` instead of `cmd` or `PowerShell` from Windows.
