### ISSUE TITLE
silesia location

### ISSUE THREAD

**Issue by JuliaLawall** [inikep/lzbench#98]
The README file points to https://drive.google.com/file/d/0BwX7dtyRLxThenZpYU9zLTZhR1k/view?usp=sharing, but this doesn't seem to lead to anything useful  The dataset is available in github: https://github.com/MiloszKrajewski/SilesiaCorpus.git

**Comment by jinfeihan57** [comment]
http://sun.aei.polsl.pl/~sdeor/index.php?page=silesia
